# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 15

      - name: Install dependencies
        run: npm install

      - name: Linter (ESLint)
        run: npm run lint

      - name: Formatter (Prettier)
        run: npm run prettier

      - name: Test (Jest)
        run: npm run test

      - name: Build
        run: npm run build
